name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hey
    runs-on: ubuntu20.04
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Greetings!'' first issue'
        pr-message: 'Greetings'' first pr'
